### PR TITLE
Upgrade WebSocket4Net library to v0.15.2 via nuget

### PR DESCRIPTION
**Pull request by brandesign**

### CODE REVIEW

**Comment by theonewhoshouldnotbenamed** [comment]
What platforms has this been tested on? 

I don't think a change from source to binary will work across all supported platforms

**Comment by dylanh724** [comment]
Just letting you know I saw this -- I'll get back to you shortly 👍

**Comment by dylanh724** [comment]
@theonewhoshouldnotbenamed I probably should have clarified - just looking for a **Windows 64-bit release** if going for the Amazon gift card. For any other platforms, folks can build it themselves (or make a pull request for a release). Ideally we'd have all supported platforms, *one day*:tm:

I have been told it works on Mac/iOS, too, so far. I'll need to go back and make sure, however.

**Review by dylanh724 — COMMENTED** [review]
We don't need this since we now use **websocket-sharp**: https://github.com/sta/websocket-sharp.

**Pull request closed without merging**
